---
- name: Install MongoDB 3.2
  hosts: all
  become: true
  tasks:
  # Добавим ключ репозитория для последующей работы с ним
  - name: Add APT key
    apt_key:
      id: EA312927
      keyserver: keyserver.ubuntu.com

  - name: Add APT repository
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
      state: present
      filename: mongodb-org-4.2
      update_cache: yes

  - name: Install mongodb package
    apt:
      name: mongodb-org
      state: present

  - name: Configure service supervisor
    systemd:
      name: mongod
      enabled: yes
